### ISSUE TITLE
Cursor

### ISSUE THREAD

**Issue by jslysz** [databucket/databucket-app#19]
The cursor is active in the headings of the following dialog boxes:

![change](https://user-images.githubusercontent.com/72385787/116005467-540c3480-a607-11eb-9886-b8c385b79978.jpg)
![login](https://user-images.githubusercontent.com/72385787/116005468-54a4cb00-a607-11eb-9471-e83b6f472a0b.jpg)
![select](https://user-images.githubusercontent.com/72385787/116005469-54a4cb00-a607-11eb-87b9-28b10a48e8d2.jpg)

**Comment by kslysz** [comment]
This error could not be reproduced in v3.0.5
